#!/bin/bash
# Render 部署指南

echo "🚀 Render 部署步骤"
echo ""
echo "由于仓库是私有的，需要通过 Render 控制台连接 GitHub："
echo ""
echo "1. 访问 https://dashboard.render.com/"
echo ""
echo "2. 点击 'New +' → 'Web Service'"
echo ""
echo "3. 点击 'Connect GitHub' 授权 Render 访问你的 GitHub"
echo ""
echo "4. 选择仓库: Nami3Piece/twitter-monitor"
echo ""
echo "5. 配置服务："
echo "   - Name: twitter-monitor"
echo "   - Region: Singapore"
echo "   - Branch: main"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: python3 main.py"
echo ""
echo "6. 添加环境变量（Environment Variables）："
echo "   - ANTHROPIC_API_KEY"
echo "   - WEB_USER"
echo "   - WEB_PASSWORD"
echo "   - TWITTER_BEARER_TOKEN"
echo "   - TWITTER_API_KEY"
echo "   - TWITTER_API_SECRET"
echo "   - TWITTER_ACCESS_TOKEN"
echo "   - TWITTER_ACCESS_SECRET"
echo "   - TELEGRAM_BOT_TOKEN"
echo "   - TELEGRAM_CHAT_ID"
echo ""
echo "7. 点击 'Create Web Service'"
echo ""
echo "✅ 部署完成后，新功能将自动生效！"
echo ""
echo "📦 GitHub 仓库: https://github.com/Nami3Piece/twitter-monitor"
echo "🔑 Render API Key: rnd_9kfvpHUcgnD7P5O9nWTpz4Rejgu6"
