#!/bin/bash
# PythonAnywhere 部署指南

echo "🚀 PythonAnywhere 免费部署方案"
echo ""
echo "PythonAnywhere 提供真正的免费套餐，无需信用卡"
echo ""
echo "步骤："
echo ""
echo "1. 注册账号: https://www.pythonanywhere.com/registration/register/beginner/"
echo "   - 完全免费"
echo "   - 不需要信用卡"
echo ""
echo "2. 登录后，打开 Bash 控制台"
echo ""
echo "3. 克隆代码:"
echo "   git clone https://github.com/Nami3Piece/twitter-monitor.git"
echo "   cd twitter-monitor"
echo ""
echo "4. 安装依赖:"
echo "   pip3 install --user -r requirements.txt"
echo ""
echo "5. 设置环境变量（在 .env 文件中）"
echo ""
echo "6. 在 Web 标签页创建新的 Web App:"
echo "   - Python 3.9"
echo "   - Manual configuration"
echo "   - WSGI file: 指向 main.py"
echo ""
echo "7. 启动服务"
echo ""
echo "✅ 你的服务将运行在: https://你的用户名.pythonanywhere.com"
echo ""
echo "📦 代码已准备好: https://github.com/Nami3Piece/twitter-monitor"
